### ISSUE TITLE
/edit broken

### ISSUE THREAD

**Issue by chunned** [chunned/databass#65]
http://192.168.0.12:10111/edit/316
Internal Server Error

**Comment by chunned** [comment]
```
ERROR] Error handling request /edit/316                                                                                                                            
databass  | Traceback (most recent call last):                                                                                                                                                                    
databass  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 134, in handle                                                                                                        
databass  |     self.handle_request(listener, req, client, addr)                                                                                                                                                  
databass  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 177, in handle_request                                                                                                
databass  |     respiter = self.wsgi(environ, resp.start_response)                                                                                                                                                databass  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__                                                                                                                 databass  |     return self.wsgi_app(environ, start_response)                                                                                                                                                     
databass  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                     databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1476, in wsgi_app                                                                                                                 databass  |     response = self.handle_exception(e)                                                                                                                                                               
databass  |                ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                               
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
databass  |     response = self.full_dispatch_request()
databass  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
databass  |     rv = self.handle_user_exception(e)                                                       
databass  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
databass  |     rv = self.dispatch_request()
databass  |          ^^^^^^^^^^^^^^^^^^^^^^^
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
databass  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
databass  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
databass  |   File "/databass/routes.py", line 303, in edit
databass  |     release_data = db.exists(item_type='release', item_id=release_id)[0]
databass  |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
databass  | TypeError: 'Release' object is not subscriptable
postgres  | 2024-09-14 03:51:32.732 UTC [27] LOG:  checkpoint starting: time
postgres  | 2024-09-14 03:51:34.416 UTC [27] LOG:  checkpoint complete: wrote 14 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.325 s, sync=0.194 s, total=1.685 s; sync files=14, longest=0.
176 s, average=0.014 s; distance=52 kB, estimate=52 kB; lsn=0/1C54938, redo lsn=0/1C54900
databass  | 
databass  | Target amount: 1000 - Actual amount: 608
databass  | {'release': {'id': 'b2f16155-1623-4c9a-94df-d422bb5cb0bc', 'title': 'The Queen Is Dead', 'status': 'Official', 'quality': 'normal', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'dat
e': '1986', 'country': 'JP', 'release-event-list': [{'date': '1986', 'area': {'id': '2db42837-c832-3c27-b4a3-08198f75693c', 'name': 'Japan', 'sort-name': 'Japan', 'iso-3166-1-code-list': ['JP']}}], 'release-eve
nt-count': 1, 'cover-art-archive': {'artwork': 'false', 'count': '0', 'front': 'false', 'back': 'false'}, 'medium-list': [{'position': '1', 'format': 'CD', 'track-list': [{'id': '5bc8132f-0f56-4fbb-8ae2-8d2b6b5
7b01a', 'position': '1', 'number': '1', 'title': 'The Queen Is Dead (Take Me Back to Dear Old Blighty (medley))', 'length': '383000', 'recording': {'id': 'a054c935-a346-4533-92f4-00e0ed590680', 'title': 'The Qu
een Is Dead', 'length': '384333'}, 'track_or_recording_length': '383000'}, {'id': '0ccc26d0-023f-4fe1-a286-22150ed25190', 'position': '2', 'number': '2', 'length': '137000', 'recording': {'id': 'a9e06b60-9c61-4
a04-9be1-7abb7e281c59', 'title': 'Frankly, Mr. Shankly', 'length': '139226'}, 'track_or_recording_length': '137000'}, {'id': '04e4dbca-9812-427b-a33a-1f8f2d0d0f5d', 'position': '3', 'number': '3', 'length': '34
8000', 'recording': {'id': 'c0dbdec0-17c5-4b47-8e3a-9fd5d2a09305', 'title': 'I Know It’s Over', 'length': '349733'}, 'track_or_recording_length': '348000'}, {'id': '896559bc-22ac-440d-a8b7-8f5dee86323b', 'posit
ion': '4', 'number': '4', 'length': '216000', 'recording': {'id': '52caf2de-5f68-4ffc-8ace-3cf937f3f2e8', 'title': 'Never Had No One Ever', 'length': '217306'}, 'track_or_recording_length': '216000'}, {'id': '0
5876ccf-b8d9-490f-a6c6-005c44693da7', 'position': '5', 'number': '5', 'title': 'Cemetry Gates', 'length': '159000', 'recording': {'id': '03c2ee5d-ee00-416c-8237-1e5fc60cb714', 'title': 'Cemetary Gates', 'length
': '161000'}, 'track_or_recording_length': '159000'}, {'id': '0d1473f3-b7f3-456f-b915-f303eeaf7df0', 'position': '6', 'number': '6', 'length': '192000', 'recording': {'id': '2c5ffe3e-509e-4607-9b4c-e846b4b50e0f
', 'title': 'Bigmouth Strikes Again', 'length': '193800'}, 'track_or_recording_length': '192000'}, {'id': '3898c9a3-7cff-4c3b-892e-d497d628694a', 'position': '7', 'number': '7', 'length': '195000', 'recording':
 {'id': '958fd167-0305-4021-85fc-e8ee5cc7fc45', 'title': 'The Boy With the Thorn in His Side', 'length': '197106'}, 'track_or_recording_length': '195000'}, {'id': 'cd78a6ce-86d1-4f88-a836-a2a08689d6ce', 'positi
on': '8', 'number': '8', 'length': '141000', 'recording': {'id': 'f3f14db5-36a8-4e0b-8291-5d62c5b43e74', 'title': 'Vicar in a Tutu', 'length': '142360'}, 'track_or_recording_length': '141000'}, {'id': '208acb2d
-f4fe-4a03-894e-75ab57d4a612', 'position': '9', 'number': '9', 'length': '242000', 'recording': {'id': 'f87a0c54-60ef-4db1-9628-96677504692d', 'title': 'There Is a Light That Never Goes Out', 'length': '243266'
}, 'track_or_recording_length': '242000'}, {'id': 'b3f6d06f-6415-490b-8567-51b462d68f52', 'position': '10', 'number': '10', 'length': '194000', 'recording': {'id': '25411ee0-663d-45a8-add3-cdd65d4cc71c', 'title
': 'Some Girls Are Bigger Than Others', 'length': '195826'}, 'track_or_recording_length': '194000'}], 'track-count': 10}], 'medium-count': 1}}
databass  | [{'id': '5bc8132f-0f56-4fbb-8ae2-8d2b6b57b01a', 'position': '1', 'number': '1', 'title': 'The Queen Is Dead (Take Me Back to Dear Old Blighty (medley))', 'length': '383000', 'recording': {'id': 'a05
4c935-a346-4533-92f4-00e0ed590680', 'title': 'The Queen Is Dead', 'length': '384333'}, 'track_or_recording_length': '383000'}, {'id': '0ccc26d0-023f-4fe1-a286-22150ed25190', 'position': '2', 'number': '2', 'len
gth': '137000', 'recording': {'id': 'a9e06b60-9c61-4a04-9be1-7abb7e281c59', 'title': 'Frankly, Mr. Shankly', 'length': '139226'}, 'track_or_recording_length': '137000'}, {'id': '04e4dbca-9812-427b-a33a-1f8f2d0d
0f5d', 'position': '3', 'number': '3', 'length': '348000', 'recording': {'id': 'c0dbdec0-17c5-4b47-8e3a-9fd5d2a09305', 'title': 'I Know It’s Over', 'length': '349733'}, 'track_or_recording_length': '348000'}, {
'id': '896559bc-22ac-440d-a8b7-8f5dee86323b', 'position': '4', 'number': '4', 'length': '216000', 'recording': {'id': '52caf2de-5f68-4ffc-8ace-3cf937f3f2e8', 'title': 'Never Had No One Ever', 'length': '217306'
}, 'track_or_recording_length': '216000'}, {'id': '05876ccf-b8d9-490f-a6c6-005c44693da7', 'position': '5', 'number': '5', 'title': 'Cemetry Gates', 'length': '159000', 'recording': {'id': '03c2ee5d-ee00-416c-82
37-1e5fc60cb714', 'title': 'Cemetary Gates', 'length': '161000'}, 'track_or_recording_length': '159000'}, {'id': '0d1473f3-b7f3-456f-b915-f303eeaf7df0', 'position': '6', 'number': '6', 'length': '192000', 'reco
rding': {'id': '2c5ffe3e-509e-4607-9b4c-e846b4b50e0f', 'title': 'Bigmouth Strikes Again', 'length': '193800'}, 'track_or_recording_length': '192000'}, {'id': '3898c9a3-7cff-4c3b-892e-d497d628694a', 'position': 
'7', 'number': '7', 'length': '195000', 'recording': {'id': '958fd167-0305-4021-85fc-e8ee5cc7fc45', 'title': 'The Boy With the Thorn in His Side', 'length': '197106'}, 'track_or_recording_length': '195000'}, {'
id': 'cd78a6ce-86d1-4f88-a836-a2a08689d6ce', 'position': '8', 'number': '8', 'length': '141000', 'recording': {'id': 'f3f14db5-36a8-4e0b-8291-5d62c5b43e74', 'title': 'Vicar in a Tutu', 'length': '142360'}, 'tra
ck_or_recording_length': '141000'}, {'id': '208acb2d-f4fe-4a03-894e-75ab57d4a612', 'position': '9', 'number': '9', 'length': '242000', 'recording': {'id': 'f87a0c54-60ef-4db1-9628-96677504692d', 'title': 'There
 Is a Light That Never Goes Out', 'length': '243266'}, 'track_or_recording_length': '242000'}, {'id': 'b3f6d06f-6415-490b-8567-51b462d68f52', 'position': '10', 'number': '10', 'length': '194000', 'recording': {
'id': '25411ee0-663d-45a8-add3-cdd65d4cc71c', 'title': 'Some Girls Are Bigger Than Others', 'length': '195826'}, 'track_or_recording_length': '194000'}]
databass  | INFO: No square images found.
databass  | INFO: No square images found.
databass  | img or img_type was blank; requires manual debug
```
side note: really need to clean up debug messages when i find some time

**Comment by chunned** [comment]
```shell
postgres  | 2024-09-17 03:24:22.551 UTC [33] ERROR:  null value in column "name" of relation "release" violates not-null constraint                                                                               
postgres  | 2024-09-17 03:24:22.551 UTC [33] DETAIL:  Failing row contains (625, null, 0, 0, null, 1985, null, null, 2024-06-02 00:00:00, null, United States, rock, None, http://coverartarchive.org/release/7db8
a368-ca76-343f-a6dd-f6ad6..., null).                                                                                                                                                                              
postgres  | 2024-09-17 03:24:22.551 UTC [33] STATEMENT:  INSERT INTO release (mbid, artist_id, label_id, name, release_year, runtime, rating, listen_date, track_count, country, genre, tags, image, review) VALUE
S (NULL, 0, 0, NULL, '1985', NULL, NULL, '2024-06-02 00:00:00', NULL, 'United States', 'rock', 'None', 'http://coverartarchive.org/release/7db8a368-ca76-343f-a6dd-f6ad604f630b/25290697827.jpg', NULL) RETURNING 
release.id                                                                                                                                                                                                        
databass  | [2024-09-17 03:24:22 +0000] [7] [ERROR] Error handling request /edit_release                                                                                                                          
databass  | Traceback (most recent call last):                                                                                                                                                                    
databass  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context                                                                                        
databass  |     self.dialect.do_execute(                                                                                                                                                                          
databass  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute                                                                                                
databass  |     cursor.execute(statement, parameters)
databass  | psycopg2.errors.NotNullViolation: null value in column "name" of relation "release" violates not-null constraint
databass  | DETAIL:  Failing row contains (625, null, 0, 0, null, 1985, null, null, 2024-06-02 00:00:00, null, United States, rock, None, http://coverartarchive.org/release/7db8a368-ca76-343f-a6dd-f6ad6..., nul
l).    
```
