### ISSUE TITLE
KeyError: 'length' on release submission

### ISSUE THREAD

**Issue by chunned** [chunned/databass#80]
```python
databass  | {'release': {'id': 'b307e32b-b4f3-45af-8a41-21b2416a3177', 'title': 'Superfuzz Bigmuff', 'status': 'Official', 'quality': 'normal', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'dat
e': '1988', 'country': 'US', 'release-event-list': [{'date': '1988', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'name': 'United States', 'sort-name': 'United States', 'iso-3166-1-code-list': ['US']}
}], 'release-event-count': 1, 'cover-art-archive': {'artwork': 'true', 'count': '5', 'front': 'true', 'back': 'true'}, 'medium-list': [{'position': '1', 'format': '12" Vinyl', 'track-list': [{'id': '720e1894-a8
61-34a4-951d-7f12fed00fba', 'position': '1', 'number': 'A1', 'recording': {'id': 'ab6b70b4-83cb-42f2-91f8-42f4d1cdc946', 'title': 'Need', 'length': '180000'}, 'track_or_recording_length': '180000'}, {'id': 'b55
43806-0c87-3ec0-a592-0e2a4d9e3a92', 'position': '2', 'number': 'A2', 'recording': {'id': 'b02d51a5-8c57-47ca-a172-ad4d1b6e9b95', 'title': 'Chain That Door'}}, {'id': '917834bb-a964-3a73-bdb5-72c96146d45c', 'pos
ition': '3', 'number': 'A3', 'recording': {'id': '4d994f46-e0a0-4e18-8817-ccaeb5360552', 'title': 'Mudride', 'length': '344000'}, 'track_or_recording_length': '344000'}, {'id': 'd0169a11-6618-349a-8c04-3bee1eae
2159', 'position': '4', 'number': 'B1', 'recording': {'id': '3d14675b-c395-4de9-9493-866af1035871', 'title': 'No One Has', 'length': '206000'}, 'track_or_recording_length': '206000'}, {'id': '007495c6-84f4-350c
-b55f-1a872111bf78', 'position': '5', 'number': 'B2', 'recording': {'id': '4fb4d78b-01da-4213-83ab-4e16f4f8bce9', 'title': 'If I Think', 'length': '217000'}, 'track_or_recording_length': '217000'}, {'id': 'c7ce
992d-94cb-352e-b27c-b4eb09b75955', 'position': '6', 'number': 'B3', 'recording': {'id': 'b4ea8ac1-cb55-4a9c-8949-6dc5a01964f8', 'title': 'In ’n’ Out of Grace', 'length': '331000'}, 'track_or_recording_length': 
'331000'}], 'track-count': 6}], 'medium-count': 1}}                                                      
databass  | [{'id': '720e1894-a861-34a4-951d-7f12fed00fba', 'position': '1', 'number': 'A1', 'recording': {'id': 'ab6b70b4-83cb-42f2-91f8-42f4d1cdc946', 'title': 'Need', 'length': '180000'}, 'track_or_recording
_length': '180000'}, {'id': 'b5543806-0c87-3ec0-a592-0e2a4d9e3a92', 'position': '2', 'number': 'A2', 'recording': {'id': 'b02d51a5-8c57-47ca-a172-ad4d1b6e9b95', 'title': 'Chain That Door'}}, {'id': '917834bb-a9
64-3a73-bdb5-72c96146d45c', 'position': '3', 'number': 'A3', 'recording': {'id': '4d994f46-e0a0-4e18-8817-ccaeb5360552', 'title': 'Mudride', 'length': '344000'}, 'track_or_recording_length': '344000'}, {'id': '
d0169a11-6618-349a-8c04-3bee1eae2159', 'position': '4', 'number': 'B1', 'recording': {'id': '3d14675b-c395-4de9-9493-866af1035871', 'title': 'No One Has', 'length': '206000'}, 'track_or_recording_length': '2060
00'}, {'id': '007495c6-84f4-350c-b55f-1a872111bf78', 'position': '5', 'number': 'B2', 'recording': {'id': '4fb4d78b-01da-4213-83ab-4e16f4f8bce9', 'title': 'If I Think', 'length': '217000'}, 'track_or_recording_
length': '217000'}, {'id': 'c7ce992d-94cb-352e-b27c-b4eb09b75955', 'position': '6', 'number': 'B3', 'recording': {'id': 'b4ea8ac1-cb55-4a9c-8949-6dc5a01964f8', 'title': 'In ’n’ Out of Grace', 'length': '331000'
}, 'track_or_recording_length': '331000'}]
databass  | {'release': {'id': 'b307e32b-b4f3-45af-8a41-21b2416a3177', 'title': 'Superfuzz Bigmuff', 'status': 'Official', 'quality': 'normal', 'text-representation': {'language': 'eng', 'script': 'Latn'}, 'dat
e': '1988', 'country': 'US', 'release-event-list': [{'date': '1988', 'area': {'id': '489ce91b-6658-3307-9877-795b68554c98', 'name': 'United States', 'sort-name': 'United States', 'iso-3166-1-code-list': ['US']}
}], 'release-event-count': 1, 'cover-art-archive': {'artwork': 'true', 'count': '5', 'front': 'true', 'back': 'true'}, 'medium-list': [{'position': '1', 'format': '12" Vinyl', 'track-list': [{'id': '720e1894-a8
61-34a4-951d-7f12fed00fba', 'position': '1', 'number': 'A1', 'recording': {'id': 'ab6b70b4-83cb-42f2-91f8-42f4d1cdc946', 'title': 'Need', 'length': '180000'}, 'track_or_recording_length': '180000'}, {'id': 'b55
43806-0c87-3ec0-a592-0e2a4d9e3a92', 'position': '2', 'number': 'A2', 'recording': {'id': 'b02d51a5-8c57-47ca-a172-ad4d1b6e9b95', 'title': 'Chain That Door'}}, {'id': '917834bb-a964-3a73-bdb5-72c96146d45c', 'pos
ition': '3', 'number': 'A3', 'recording': {'id': '4d994f46-e0a0-4e18-8817-ccaeb5360552', 'title': 'Mudride', 'length': '344000'}, 'track_or_recording_length': '344000'}, {'id': 'd0169a11-6618-349a-8c04-3bee1eae
2159', 'position': '4', 'number': 'B1', 'recording': {'id': '3d14675b-c395-4de9-9493-866af1035871', 'title': 'No One Has', 'length': '206000'}, 'track_or_recording_length': '206000'}, {'id': '007495c6-84f4-350c
-b55f-1a872111bf78', 'position': '5', 'number': 'B2', 'recording': {'id': '4fb4d78b-01da-4213-83ab-4e16f4f8bce9', 'title': 'If I Think', 'length': '217000'}, 'track_or_recording_length': '217000'}, {'id': 'c7ce
992d-94cb-352e-b27c-b4eb09b75955', 'position': '6', 'number': 'B3', 'recording': {'id': 'b4ea8ac1-cb55-4a9c-8949-6dc5a01964f8', 'title': 'In ’n’ Out of Grace', 'length': '331000'}, 'track_or_recording_length': 
'331000'}], 'track-count': 6}], 'medium-count': 1}}[2024-10-05 17:40:32 +0000] [7] [ERROR] Error handling request /submit
databass  | Traceback (most recent call last):                                                           
databass  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 134, in handle                                                                                                        
databass  |     self.handle_request(listener, req, client, addr)                                                                                                                                                  
databass  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 177, in handle_request                                                                                                
databass  |     respiter = self.wsgi(environ, resp.start_response)                                                                                                                                                
databass  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__                                                                                                                 
databass  |     return self.wsgi_app(environ, start_response)                                                                                                                                                     
databass  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                     
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1476, in wsgi_app                                                                                                                 
databass  |     response = self.handle_exception(e)                                                      
databass  |                ^^^^^^^^^^^^^^^^^^^^^^^^                                                      
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app                                                                                                                 
databass  |     response = self.full_dispatch_request()                                                  
databass  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                  
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request                                                                                                     
databass  |     rv = self.handle_user_exception(e)                                                       
databass  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request                                                                                                     
databass  |     rv = self.dispatch_request()                                                             
databass  |          ^^^^^^^^^^^^^^^^^^^^^^^                                                             
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request                                                                                                          
databass  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
databass  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                          
databass  |   File "/databass/databass/routes.py", line 135, in submit                                                                                                                                            
databass  |     runtime = MusicBrainz.get_release_length(release_mbid)                                                                                                                                            
databass  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                            
databass  |   File "/databass/databass/api/musicbrainz.py", line 225, in get_release_length                                                                                                                       
databass  |     raise e                             
databass  |   File "/databass/databass/api/musicbrainz.py", line 221, in get_release_length                                                                                                                       
databass  |     length += track["length"]                                                                
databass  |               ~~~~~^^^^^^^^^^                                                                
databass  | KeyError: 'length'           
```

**Comment by chunned** [comment]
Should be fixed in latest commit to unittests branch

Changed line 221 from 
`except TypeError or KeyError:`
to
`except TypeError | KeyError as e:`
Need to test if this actually works
