### ISSUE TITLE
Improve get_image fallback

### ISSUE THREAD

**Issue by chunned** [chunned/databass#82]
Archive.org is still down and showing no signs of being back up any time soon. Lazy solution would be to temporarily deprecate the calls to CoverArtArchive but to avoid doing this the fallback to Discogs should be improved. 

Currently, the request to CAA takes too long, causing the Gunicorn worker to time out. When this happens, no attempt is made to fetch the cover from Discogs. 

```shell
databass  | [2024-10-19 19:25:20 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:11)                                                                                                                                    
databass  | [2024-10-19 19:25:20 +0000] [11] [ERROR] Error handling request /submit                                                                                                                               
databass  | Traceback (most recent call last):                                                                                                                                                                    
databass  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 134, in handle                                                                                                        
databass  |     self.handle_request(listener, req, client, addr)                                                                                                                                                  
databass  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 177, in handle_request                                                                                                
databass  |     respiter = self.wsgi(environ, resp.start_response)                                                                                                                                                
databass  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__                                                                                                                 
databass  |     return self.wsgi_app(environ, start_response)                                                                                                                                                     
databass  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                     
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app                                                                                                                 
databass  |     response = self.full_dispatch_request()                                                                                                                                                           
databass  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                           
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request                                                                                                     
databass  |     rv = self.dispatch_request()                                                                                                                                                                      
databass  |          ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                      
databass  |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request                                                                                                          
databass  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]                                                                                           
databass  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                          
databass  |   File "/databass/databass/routes.py", line 199, in submit                                                                                                                                            
databass  |     image_filepath = Util.get_image(                                                                                                                                                                  
databass  |                      ^^^^^^^^^^^^^^^                                                                                                                                                                  
databass  |   File "/databass/databass/api/util.py", line 102, in get_image                                                                                                                                       
databass  |     img = MusicBrainz.get_image(mbid)                                                                                                                                                                 
databass  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                 
databass  |   File "/databass/databass/api/musicbrainz.py", line 239, in get_image                                                                                                                                
databass  |     return mbz.get_release_group_image_front(mbid, size='250')                                                                                                                                        
databass  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                        
databass  |   File "/usr/local/lib/python3.12/site-packages/musicbrainzngs/caa.py", line 133, in get_release_group_image_front                                                                                    
databass  |     return get_image(releasegroupid, "front", size=size,                                                                                                                                              
databass  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                              
databass  |   File "/usr/local/lib/python3.12/site-packages/musicbrainzngs/caa.py", line 187, in get_image
databass  |     return _caa_request(mbid, coverid, size=size, entitytype=entitytype)
databass  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
databass  |   File "/usr/local/lib/python3.12/site-packages/musicbrainzngs/caa.py", line 79, in _caa_request
databass  |     resp = musicbrainz._safe_read(opener, req, None)
databass  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
databass  |   File "/usr/local/lib/python3.12/site-packages/musicbrainzngs/musicbrainz.py", line 491, in _safe_read
databass  |     time.sleep(retry_num * retry_delay_delta)
databass  |   File "/usr/local/lib/python3.12/site-packages/gunicorn/workers/base.py", line 204, in handle_abort
databass  |     sys.exit(1)
databass  | SystemExit: 1
databass  | [2024-10-19 19:25:20 +0000] [11] [INFO] Worker exiting (pid: 11)
databass  | App version: 0.5
databass  | Database initialized successfully.
databass  | Routes registered.
```

Notice how it causes a full application reset.

**Comment by chunned** [comment]
Changes to `api/util.py`:
- Import `signal` library, create a custom exception `TimeoutException` and an ultra-simple `timeout_handler` function
- Set a signal with 5 second timeout before making CAA request
- If no response is received within the timeout duration, exception will be raised
